The dataset is appropriately loaded and stored into corresponding variables.

In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/taxi-fare-guru-total-amount-prediction-challenge/sample.csv.csv
/kaggle/input/taxi-fare-guru-total-amount-prediction-challenge/train.csv
/kaggle/input/taxi-fare-guru-total-amount-prediction-challenge/test.csv

In [ ]:
Loading the dataset in data frame

In [2]:
df = pd.read_csv("/kaggle/input/taxi-fare-guru-total-amount-prediction-challenge/train.csv")

EDA

In [3]:
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,extra,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee
0,1,2023-06-28 17:20:21,2023-06-28 16:34:45,1.0,2.14,1.0,N,120,9,Credit Card,2.5,7.165589,0.0,1.0,20.64,2.5,0.00
1,0,2023-06-29 23:05:01,2023-06-29 22:01:35,1.0,2.70,1.0,N,15,215,Credit Card,3.5,6.067401,0.0,1.0,25.55,2.5,0.00
2,1,2023-06-30 10:19:31,2023-06-30 11:13:10,1.0,1.15,1.0,N,167,223,Credit Card,0.0,4.111547,0.0,1.0,17.64,2.5,0.00
3,0,2023-06-29 13:23:09,2023-06-29 14:20:01,1.0,0.40,1.0,N,128,239,Credit Card,2.5,6.411079,0.0,1.0,12.80,2.5,0.00
4,1,2023-06-29 22:03:32,2023-06-29 22:22:22,3.0,1.10,1.0,N,203,52,Credit Card,1.0,4.769377,0.0,1.0,18.00,2.5,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
174995,1,2023-06-30 22:50:57,2023-06-30 22:22:22,3.0,3.45,1.0,N,147,167,Credit Card,1.0,8.732495,0.0,1.0,28.08,2.5,0.00
174996,1,2023-06-30 13:03:33,2023-06-30 14:04:57,1.0,9.44,1.0,N,154,191,Cash,5.0,0.283275,0.0,1.0,59.95,2.5,1.75
174997,0,2023-06-29 11:03:32,2023-06-29 12:13:34,1.0,2.40,1.0,N,168,106,Credit Card,2.5,4.245354,0.0,1.0,33.50,2.5,0.00
174998,1,2023-06-29 19:47:17,2023-06-29 19:08:55,1.0,4.71,1.0,N,240,100,Credit Card,2.5,10.479776,0.0,1.0,40.80,2.5,0.00
174999,1,2023-06-30 21:26:43,2023-06-30 22:54:42,1.0,1.01,1.0,N,153,72,Credit Card,1.0,6.541699,0.0,1.0,16.32,2.5,0.00


# Exploratory data analysis - Checking if pickup is after dropoff

In [4]:
from datetime import datetime

df['tpep_pickup_datetime'] = pd.to_datetime(df['tpep_pickup_datetime'])
df['tpep_dropoff_datetime'] = pd.to_datetime(df['tpep_dropoff_datetime'])

(df.tpep_pickup_datetime > df.tpep_dropoff_datetime)

0          True
1          True
2         False
3         False
4         False
          ...
174995     True
174996    False
174997    False
174998     True
174999    False
Length: 175000, dtype: bool

1. The dataset is appropriately preprocessed,
2. Feature engineering/extraction.
3. Removing unnecessary columns and defining target variable

# Data Preprocessing - Separating features and target variable

In [6]:
X = df.drop(labels = ['tpep_dropoff_datetime', 'tpep_pickup_datetime', 'total_amount'], axis=1)
y = df['total_amount']

In [9]:
X

,VendorID,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,extra,tip_amount,tolls_amount,improvement_surcharge,congestion_surcharge,Airport_fee
0,1,1.0,2.14,1.0,N,120,9,Credit Card,2.5,7.165589,0.0,1.0,2.5,0.00
1,0,1.0,2.70,1.0,N,15,215,Credit Card,3.5,6.067401,0.0,1.0,2.5,0.00
2,1,1.0,1.15,1.0,N,167,223,Credit Card,0.0,4.111547,0.0,1.0,2.5,0.00
3,0,1.0,0.40,1.0,N,128,239,Credit Card,2.5,6.411079,0.0,1.0,2.5,0.00
4,1,3.0,1.10,1.0,N,203,52,Credit Card,1.0,4.769377,0.0,1.0,2.5,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
174995,1,3.0,3.45,1.0,N,147,167,Credit Card,1.0,8.732495,0.0,1.0,2.5,0.00
174996,1,1.0,9.44,1.0,N,154,191,Cash,5.0,0.283275,0.0,1.0,2.5,1.75
174997,0,1.0,2.40,1.0,N,168,106,Credit Card,2.5,4.245354,0.0,1.0,2.5,0.00
174998,1,1.0,4.71,1.0,N,240,100,Credit Card,2.5,10.479776,0.0,1.0,2.5,0.00
174999,1,1.0,1.01,1.0,N,153,72,Credit Card,1.0,6.541699,0.0,1.0,2.5,0.00

In [ ]:
# import seaborn as sns
# from sklearn.preprocessing import MinMaxScaler

# scaler = MinMaxScaler()

# X2 = scaler.fit_transform(X1.to_numpy())
# X2 = pd.DataFrame(X2, columns=[
#         'VendorID', 'passenger_count', 'trip_distance', 'RatecodeID',
#        'store_and_fwd_flag', 'PULocationID', 'DOLocationID', 'payment_type',
#        'extra', 'tip_amount', 'tolls_amount', 'improvement_surcharge',
#        'congestion_surcharge', 'Airport_fee'])

# print("Scaled Dataset Using MinMaxScaler")
# df_scaled.head()


# Feature Engineering - Encoding categorical features

In [11]:
X1=pd.get_dummies(X,columns=['store_and_fwd_flag',
                             'payment_type'],drop_first='True')

In [12]:
X1.columns

Index(['VendorID', 'passenger_count', 'trip_distance', 'RatecodeID',
       'PULocationID', 'DOLocationID', 'extra', 'tip_amount', 'tolls_amount',
       'improvement_surcharge', 'congestion_surcharge', 'Airport_fee',
       'store_and_fwd_flag_Y', 'payment_type_Credit Card', 'payment_type_UPI',
       'payment_type_Wallet', 'payment_type_unknown'],
      dtype='object')

# Detecting missing data and imputation

In [13]:
from sklearn.impute import SimpleImputer
imp_median = SimpleImputer(missing_values=np.nan, strategy='median')
X1 = imp_median.fit_transform(X1)
# X1 = pd.DataFrame(X1, columns=[
#         'VendorID', 'passenger_count', 'trip_distance', 'RatecodeID',
#        'store_and_fwd_flag', 'PULocationID', 'DOLocationID', 'payment_type',
#        'extra', 'tip_amount', 'tolls_amount', 'improvement_surcharge',
#        'congestion_surcharge', 'Airport_fee'])


# Splitting the data into training and testing sets

In [15]:
from sklearn.model_selection import train_test_split

X1_train, X1_test, y_train, y_test = train_test_split(
    X1, y, test_size=0.2, random_state=42)


# Training and evaluating Linear Regression model

#  #hyperparameter tuning not needed used default hyperparameters

In [26]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr = lr.fit(X1_train, y_train)
lr.score(X1_test, y_test)

0.7220634860399004


# Training and evaluating Decision Tree model

In [16]:
from sklearn.tree import DecisionTreeRegressor
dtr = DecisionTreeRegressor(random_state=0)
dtr = dtr.fit(X1_train, y_train)
dtr.score(X1_test, y_test)

0.9048138476628115

# Training and evaluating Random Forest model

In [17]:
from sklearn.ensemble import RandomForestRegressor
rfr = RandomForestRegressor(random_state=0)
rfr = rfr.fit(X1_train, y_train)
rfr.score(X1_test, y_test)

0.9554459810680183


# Loading test dataset for submission

In [27]:
X2 = pd.read_csv('/kaggle/input/taxi-fare-guru-total-amount-prediction-challenge/test.csv')

In [28]:
X2 = X2.drop(labels = ['tpep_dropoff_datetime', 'tpep_pickup_datetime'], axis=1)

In [30]:
X3=pd.get_dummies(X2,columns=['store_and_fwd_flag',
                             'payment_type'],drop_first='True')

In [23]:
X3.columns

Index(['VendorID', 'passenger_count', 'trip_distance', 'RatecodeID',
       'PULocationID', 'DOLocationID', 'extra', 'tip_amount', 'tolls_amount',
       'improvement_surcharge', 'congestion_surcharge', 'Airport_fee',
       'store_and_fwd_flag_Y', 'payment_type_Credit Card', 'payment_type_UPI',
       'payment_type_Wallet', 'payment_type_unknown'],
      dtype='object')


# Imputing missing values in the test dataset

In [25]:
from sklearn.impute import SimpleImputer
imp_median = SimpleImputer(missing_values=np.nan, strategy='median')
X3 = imp_median.fit_transform(X3)

# Generating predictions for submission using the best model (Random Forest)

In [ ]:
submission = rfr.predict(X3)

In [ ]:
submission = pd.DataFrame(submission, columns=['total_amount'])

In [ ]:
submission.index.name = 'ID'
submission.index = submission.index + 1

In [ ]:
submission.to_csv("submission.csv")